/**:
  ros__parameters:
    invDepth_min_range: 0.2
    invDepth_max_range: 2.0
    TS_HISTORY_LENGTH: 100
    REF_HISTORY_LENGTH: 10
    tracking_rate_hz: 100
    patch_size_X: 1
    patch_size_Y: 1
    kernelSize: 5
    MAX_REGISTRATION_POINTS: 6000
    BATCH_SIZE: 800
    MAX_ITERATION: 10
    LSnorm: "Huber"
    huber_threshold: 50.0
    MIN_NUM_EVENTS: 4000
    RegProblemType: 1
    SAVE_TRAJECTORY: false
    PATH_TO_SAVE_TRAJECTORY: "/tmp/esvo_trajectory/"
    VISUALIZE_TRAJECTORY: true
