/**:
  ros__parameters:
    invDepth_min_range: 0.001
    invDepth_max_range: 0.25
    residual_vis_threshold: 30
    stdVar_vis_threshold: 1.0
    age_max_range: 10
    age_vis_threshold: 1
    fusion_radius: 1
    FUSION_STRATEGY: "CONST_FRAMES"  # "CONST_POINTS" or "CONST_FRAMES"
    maxNumFusionFrames: 5
    maxNumFusionPoints: 20000
    Denoising: false
    SmoothTimeSurface: true
    Regularization: true
    bVisualizeGlobalPC: true
    visualizeGPC_interval: 0.5  # (unit: s)
    NumGPC_added_per_refresh: 10000
    visualize_range: 30.0
    PROCESS_EVENT_NUM: 10000
    TS_HISTORY_LENGTH: 100
    INIT_SGM_DP_NUM_THRESHOLD: 500
    mapping_rate_hz: 20
    # DepthProblemConfig
    patch_size_X: 15
    patch_size_Y: 7
    LSnorm: "Tdist"  # Tdist or l2
    Tdist_nu: 2.182
    Tdist_scale: 17.277
    Tdist_stdvar: 59.763
    RegularizationRadius: 20
    RegularizationMinNeighbours: 32
    RegularizationMinCloseNeighbours: 32
    # EventBM parameters
    BM_half_slice_thickness: 0.001
    BM_min_disparity: 0
    BM_max_disparity: 150
    BM_step: 1
    BM_ZNCC_Threshold: 0.1
    BM_bUpDownConfiguration: false
